// owa-frontend-user/src/pages/Login/Login.tsx
import React from "react";
import "./Login.css";
import { IonInput } from "@ionic/react";

const Login: React.FC = () => {
  return (
    <div className="flex items-center justify-center min-h-screen">
      <div className="bg-white p-6 w-full max-w-sm">
        <div className="flex justify-center mb-8">
          <img src="Assets/images/Login/ollUserLogo.svg" alt="Login" />
        </div>
        <div className="mb-4">
          <div className="border-b border-gray-300" style={{ width: "98%" }}>
            <div className="ml-2">
              <h2 className="text-2xl font-medium">Login</h2>
            </div>
          </div>
        </div>
        <form>
          <div className="mb-4">
            <IonInput
              label="Enter your Mobile Number *"
              labelPlacement="floating"
              fill="outline"
              placeholder="Enter here"
              maxlength={10}
              required
              mode="md"
              type="tel"
            ></IonInput>
          </div>
          <div className="mb-4">
            <IonInput
              label="Enter your Password *"
              labelPlacement="floating"
              fill="outline"
              placeholder="Enter here"
              required
              mode="md"
              type="password"
            ></IonInput>
            <div className="pt-2 text-right flex justify-start">
              <img src="Assets/images/LoginPage/lock.svg" alt="" />
              <a
                href="#"
                className="text-red-600 ms-2 text-sm hover:text-red-700"
              >
                Forgot Password?
              </a>
            </div>
          </div>
          <button
            type="submit"
            className="w-full text-white py-2 rounded-md transition duration-200 submit-button"
          >
            Login
          </button>
          <div className="or-container my-4 flex items-center">
            <hr className="flex-grow border-gray-500" />
            <span className="mx-4 text-gray-500">OR</span>
            <hr className="flex-grow border-gray-500" />
          </div>
          <button
            type="submit"
            className="w-full py-2 rounded-md transition duration-200 otp-button"
          >
            Login using OTP
          </button>
        </form>
      </div>
    </div>
  );
};

export default Login;

// owa-frontend-admin/src/app/screens/auth/component/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { EncDecService } from 'src/app/modules/shared/services/encryption-decryption.service';
import { AuthService } from '../../auth.service';
import { UtilityService } from 'src/app/modules/shared/services/utility.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  constructor(
    private encDecService: EncDecService,
    private authService: AuthService,
    private utilityService: UtilityService
   ) { }

  loginform : FormGroup
  ngOnInit(): void {
    this.initForm();
  }


  initForm(){
    this.loginform = new FormGroup({
      user_name : new FormControl(null,[
        Validators.required,
        Validators.maxLength(10)
      ]),
      password : new FormControl(null,[Validators.required])
    })
  }

  login(){
    if(this.loginform.valid){
      
      let loginDetails = this.loginform.getRawValue();
      loginDetails.password = this.encDecService.set(loginDetails.password),
        this.authService.login(loginDetails).subscribe((res : any)=>{
          sessionStorage.setItem('userToken', JSON.stringify(res.data.token))
        })
    }
  }
}

<div class="flex items-center justify-center h-full">
  <div class="bg-white p-8 w-full max-w-md">
      <div class="flex justify-center mb-6">
          <img src="assets/images/loginPage/ollLogo.svg" alt="OLL Logo" class="h-16">
      </div>
      
      <form class="border-2 rounded-3xl shadow-md p-10" [formGroup]="loginform" (ngSubmit)="login()">
        <h2 class="text-center text-2xl font-semibold mb-6">Sign in to OLL</h2>
          <div class="mb-4 rounded-full">
              <input type="tel"
              numbersOnly
              maxlength="10"
              id="user_name" autocomplete="off"
              name="user_name"
              formControlName="user_name"
              class="form-control w-full !bg-gray-200 px-4 py-2 border !rounded-full" placeholder="Mobile Number">
          </div>
          <div class="mb-4 relative">
            <input type="password"
              id="password"
              placeholder="Enter password"
              name="password"
              formControlName="password"
              matInput 
              class="form-control w-full !bg-gray-200 px-4 py-2 border !rounded-full"
              [type]="passwordFieldType"
              placeholder="Password">
              <i [ngClass]="{'fa-eye': isPasswordVisible, 'fa-eye-slash': !isPasswordVisible}"
              (click)="togglePasswordVisibility()" id="togglePassword" class="toggle-eye fas fa-eye-slash absolute right-3 top-1/2 transform -translate-y-1/2 text-red-600 cursor-pointer"></i>
          </div>
          <div class="mb-4 text-right flex justify-end">
            <img src="assets/images/loginPage/lock.svg" alt="" />
            <a href="#" class="text-red-600 ms-2 text-sm hover:text-red-600" [routerLink]="['/login/forgot-password']">Forgot Password?</a>
          </div>
          <button type="submit" class="w-full bg-red-600 text-white py-2 rounded-full hover:bg-red-600 transition duration-200 font-semibold">Login</button>
          <div class="flex items-center my-6">
            <hr class="flex-grow border-gray-300">
            <span class="mx-4 text-gray-500">OR</span>
            <hr class="flex-grow border-gray-300">
        </div>
        <div class="w-full bg-gray-100 text-red-600 font-semibold py-2 rounded-full hover:bg-gray-200 transition duration-200 border border-1 text-center">
          <a href="#" [routerLink]="['/login/login-otp']">Login using OTP</a>
        </div>

      </form>  
  </div>
</div>
