// owa-frontend-user/src/pages/auth/Components/ForgotPassword/ForgotPassword.tsx
import { IonInput } from "@ionic/react";
import React from "react";
import "./ForgotPassword.css"

const ForgotPassword: React.FC = () => {
  return (
    <div className="flex items-center justify-center min-h-screen">
      <div className="bg-white p-6 w-full max-w-sm">
        <div className="flex justify-center mb-8">
          <img src="Assets/images/Login/ollUserLogo.svg" alt="Login" />
        </div>
        <div className="mb-4">
          <div className="border-b border-gray-300" style={{ width: "98%" }}>
            <div className="ml-2">
              <h2 className="text-2xl font-medium">Forgot Password</h2>
            </div>
          </div>
        </div>
        <form>
          <div className="mb-4">
            <IonInput
              label="Enter your Mobile Number *"
              labelPlacement="floating"
              fill="outline"
              placeholder="Enter here"
              maxlength={10}
              required
              mode="md"
              type="tel"
            ></IonInput>
          </div>

          <button
            type="submit"
            className="w-full py-2 rounded-md transition duration-200 text-white otp-btn"
          >
            Send OTP
          </button>
        </form>
      </div>
    </div>
  );
};

export default ForgotPassword;

// owa-frontend-admin/src/app/screens/auth/component/forgot-password/forgot-password.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-forgot-password',
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.scss']
})
export class ForgotPasswordComponent {
  currentScreen = 'sendOtp';
  forgotPasswordForm: FormGroup;

  constructor(private fb: FormBuilder) {
    this.forgotPasswordForm = this.fb.group({
        mobileNumber: ['', Validators.required],
        otp: ['', Validators.required],
        newPassword: ['', Validators.required],
        confirmPassword: ['', Validators.required]
    });
}

  sendOtp() {
    this.currentScreen = 'enterOtp';
}

verifyOtp() {
    this.currentScreen = 'resetPassword';
}

resetPassword() {
    const newPassword = this.forgotPasswordForm.get('newPassword').value;
    const confirmPassword = this.forgotPasswordForm.get('confirmPassword').value;
    if (newPassword === confirmPassword) {
        alert('Password reset successful');
    } else {
        alert('Passwords do not match');
    }
}

}

<div class="flex flex-col items-center justify-center h-full p-8">
    <div class="flex justify-center mb-6">
        <img src="assets/images/loginPage/ollLogo.svg" alt="OLL Logo" class="h-16">
    </div>
   <div class="bg-white p-10 border-2 rounded-3xl shadow-lg w-full max-w-md">
        <div *ngIf="currentScreen === 'sendOtp'">
            <div class="text-center mb-6">
                <h2 class="text-2xl font-semibold">Forgot Password</h2>
            </div>
            <form [formGroup]="forgotPasswordForm" (ngSubmit)="sendOtp()">
                <input type="text" formControlName="mobileNumber" placeholder="Mobile Number" class="form-control w-full px-4 py-2 mb-4 border rounded-full bg-gray-200">
                <button type="submit" class="w-full bg-red-600 text-white py-2 rounded-full mt-4">Send OTP</button>
            </form>
        </div>

        <div *ngIf="currentScreen === 'enterOtp'">
            <div class="text-center mb-6">
                <h2 class="text-2xl font-semibold">Enter OTP</h2>
            </div>
            <form [formGroup]="forgotPasswordForm" (ngSubmit)="verifyOtp()">
                <input type="text" formControlName="otp" placeholder="OTP" class="form-control w-full px-4 py-2 mb-4 border rounded-full bg-gray-200">
                <button type="submit" class="w-full bg-red-600 text-white py-2 rounded-full mt-4">Verify</button>
            </form>
        </div>

        <div *ngIf="currentScreen === 'resetPassword'">
            <div class="text-center mb-6">
                <h2 class="text-2xl font-semibold">Reset Password</h2>
            </div>
            <form [formGroup]="forgotPasswordForm" (ngSubmit)="resetPassword()">
                <input type="password" formControlName="newPassword" placeholder="New Password" class="form-control w-full px-4 py-2 mb-4 border rounded-full bg-gray-200">
                <input type="password" formControlName="confirmPassword" placeholder="Confirm Password" class="form-control w-full px-4 py-2 mb-4 border rounded-full bg-gray-200">
                <button type="submit" class="w-full bg-red-600 text-white py-2 rounded-full mt-4">Submit</button>
            </form>
        </div>
    </div>
</div>
